server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s           # 로그를 전송하기 전에 대기하는 시간 (기본값: 1s)
    batchsize: 1048576      # 한 번에 전송하는 최대 바이트 수 (기본값: 1,048,576 bytes)

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        replacement: '$1'
        target_label: container_name
